server:
  port: 7010

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7011.com:7011/eureka/
  instance:
    hostname: eureka7010.com
